
export const transactionsConstants = {
    GETALL_REQUEST: 'TRANSACTIONS_GETALL_REQUEST',
    GETALL_SUCCESS: 'TRANSACTIONS_GETALL_SUCCESS',
    GETALL_FAILURE: 'TRANSACTIONS_GETALL_FAILURE',

    DELETE_REQUEST: 'TRANSACTION_DELETE_REQUEST',
    DELETE_SUCCESS: 'TRANSACTION_DELETE_SUCCESS',
    DELETE_FAILURE: 'TRANSACTION_DELETE_FAILURE',

    ADD_REQUEST: 'TRANSACTION_ADD_REQUEST',
    ADD_SUCCESS: 'TRANSACTION_ADD_SUCCESS',
    ADD_FAILURE: 'TRANSACTION_ADD_FAILURE',

    GETBANKS_REQUEST: 'GETBANKS_REQUEST',
    GETBANKS_SUCCESS: 'GETBANKS_SUCCESS',
    GETBANKS_FAILURE: 'GETBANKS_FAILURE'
};

export const userConstants = {
    LOGIN_REQUEST: 'USER_LOGIN_REQUEST',
    LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    LOGIN_FAILURE: 'USER_LOGIN_FAILURE',

    LOGOUT: 'USER_LOGOUT',
}

