export const ADD_ARTICLE = "ADD_ARTICLE";


export const transactionsConstants = {
    GETALL_REQUEST: 'TRANSACTIONS_GETALL_REQUEST',
    GETALL_SUCCESS: 'TRANSACTIONS_GETALL_SUCCESS',
    GETALL_FAILURE: 'TRANSACTIONS_GETALL_FAILURE',

    DELETE_REQUEST: 'TRANSACTION_DELETE_REQUEST',
    DELETE_SUCCESS: 'TRANSACTION_DELETE_SUCCESS',
    DELETE_FAILURE: 'TRANSACTION_DELETE_FAILURE',

    ADD_REQUEST: 'TRANSACTION_ADD_REQUEST',
    ADD_SUCCESS: 'TRANSACTION_ADD_SUCCESS',
    ADD_FAILURE: 'TRANSACTION_ADD_FAILURE'
};

export const userConstants = {
    LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
    LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
    LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',

    LOGOUT: 'USERS_LOGOUT',
}

